### PR TITLE
Update Developer Guide - Non-Functional Requirements

### PR DESCRIPTION
**Pull request by ghost**
Update developer guide for non-functional requirements

### CODE REVIEW

**Review by JonathanHoshi — APPROVED** [review]
Good Job! Try and minimize deleting additional information in the future as it might cause unnecessary conflicts with others and some of us might want to use it as a guideline to write their information.

**Review by arcornior — APPROVED** [review]
LGTM

**Review by arcornior — CHANGES_REQUESTED** [review]
Would it be possible to undo the deleted lines?

**Comment by lowkaiwei98** [comment]
> Would it be possible to undo the deleted lines?

Added back

**Review by arcornior — APPROVED** [review]
LGTM

**Pull request merged**
