### PR TITLE
Update User Guide - Delete

### PR DESCRIPTION
**Pull request by ghost**
Update user guide for delete

### CODE REVIEW

**Review by arcornior — APPROVED** [review]
LGTM. Would it be possible to not delete too much documentation for ease of future reference next time?

**Review by arcornior — CHANGES_REQUESTED** [review]
Would it be possible to add back the deleted lines?

**Comment by lowkaiwei98** [comment]
> 



> Would it be possible to add back the deleted lines?

Added back.

**Review by arcornior — APPROVED** [review]
LGTM

**Review by aweijun — APPROVED** [review]
LGTM, Thanks for adding back the deleted stuff!

**Pull request merged**
